version: '3'
services:
# MySQL
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
  # Client
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Server
  server:
    build:
      context: ./Server
    ports:
      - "8080:8080"
    depends_on:
      - db

  