name: Build and push docker image
on: workflow_dispatch
jobs:
  build_and_deply:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install deps
        run: npm ci
        working-directory: ./client
      - name: build
        run: npm run build
        working-directory: ./client
      - name: Install server deps
        run: npm ci
        working-directory: ./server
      - name: Build image
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: docker.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"